services:
  backend:
    build:
      context: ./api
    container_name: laravel_backend
    volumes:
      - ./api:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=movies_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www
      - ./api/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    build:
      context: ./web
    container_name: vue_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: movies_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
